
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Photo(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

 wire [9:0] h_addr,v_addr;
 wire [23:0] vga_data;
	assign VGA_SYNC_N=0;


//=======================================================
//  Structural coding
//=======================================================

	clkgen #(25000000) my_vgaclk(CLOCK2_50,1'b0,1'b1,VGA_CLK);
	
	vga_ctrl my_ctrl(VGA_CLK,1'b0,vga_data,h_addr,v_addr,VGA_HS,VGA_VS,VGA_BLANK_N,VGA_R,VGA_G,VGA_B);
	getcolor(VGA_CLK,h_addr,v_addr,vga_data);

endmodule
