
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LFSR(

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);

wire C;
wire D;



//=======================================================
//  REG/WIRE declarations
//=======================================================

	shift_register sft1(KEY[0],C,3'b101,8'b00000000,LEDR[7:0]);
	
	nor nor1(D,LEDR[1],LEDR[2],LEDR[3],LEDR[4],LEDR[5],LEDR[6],LEDR[7]);
	xor xor1(C,LEDR[0],LEDR[2],LEDR[3],LEDR[4],D);
	
	decode_hex hex0(LEDR[3:0],HEX0);
	decode_hex hex1(LEDR[7:4],HEX1);	
	


//=======================================================
//  Structural coding
//=======================================================



endmodule
